esphome:
  name: intex-pure-spa
  friendly_name: Intex Pure Spa
  platformio_options:
    board_build.f_cpu: 160000000L

esp8266:
  board: d1_mini

external_components:
  - source:
      type: local
      path: components

logger:

api:
  encryption:
    key: "..."

ota:
  - platform: esphome
    password: "..."

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

climate:

sensor:

switch:

text_sensor:

intexsbh20:
  climate:
    name: Thermostat
    icon: mdi:hot-tub
  power:
    name: Power
    icon: mdi:power
  filter:
    name: Filter
    icon: mdi:air-filter
  bubble:
    name: Bubble
    icon: mdi:chart-bubble
  water_temperature:
    name: Water temperature
    icon: mdi:water-thermometer
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 0
    unit_of_measurement: °C
  error_text:
    name: Error
    icon: mdi:alert-circle
    entity_category: diagnostic
